#!/bin/bash -exu

cd `dirname $0`
HEREDIR=`pwd`
cd "$HEREDIR/.."
ROOTDIR=`pwd`

rm -rvf "$ROOTDIR/Gemfile.lock" "$ROOTDIR/sql/run" "$ROOTDIR/sql/data"
dropdb --if-exists partitionpoc

"$HEREDIR/bootstrap"


